#!/usr/bin/env python3
"""Write part A of bilingual C01: header through end of secI_1."""
out = open('Healing_Bilingual/ops/xhtml/C01_chapter.xhtml', 'w', encoding='utf-8')
out.write('''\
<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en" xml:lang="en">
<head>
<title>Healing the Fragmented Selves of Trauma Survivors</title>
<link href="../styles/stylesheet.css" rel="stylesheet" type="text/css"/>
<meta content="urn:uuid:e0000000-0000-0000-0000-000004813485" name="Adept.expected.resource"/>
</head>
<body>
<section epub:type="introduction">
<h2 class="h2a" id="chapter101"><span epub:type="pagebreak" id="page_1"/><a class="nounder" href="B07_toc.xhtml#Rchapter101">Introduction</a></h2>
<h2 class="h2a trans-zh" lang="zh-CN">引言</h2>
<div class="h3_div">
<h3 class="h3" id="secI_1">How This Book Came To Be</h3>
<h3 class="h3 trans-zh" lang="zh-CN">本书的诞生</h3>
<p class="noindent">Having no way to understand the entrenched self-alienation or intense self-hatred of their traumatized clients, therapists often feel frustrated, baffled, and inadequate to the task of trying to help. Why do they seem to be at war with themselves? Or with us? Although the client has come seeking relief from a burden of trauma-related symptoms and issues, the task of exchanging self-alienation for self-compassion can feel overwhelming or distasteful. Neither client nor therapist has a language with which to explain the internal struggles being played out inside the client&#8217;s mind and body. In a mental health world that rejects the notion that personality and identity can be fragmented and compartmentalized, therapists are rarely trained to see the splits, much less the life-or-death battle for control being waged by &#8220;selves&#8221; with opposite aims and instincts.</p>
<p class="noindent trans-zh" lang="zh-CN">面对来访者根深蒂固的自我疏离或强烈的自我憎恨，治疗师往往感到沮丧、困惑，觉得自己无力胜任帮助他人的工作。为什么他们似乎总是在与自己交战？或是与我们交战？尽管来访者带着创伤相关症状和困扰的重担前来寻求解脱，但将自我疏离转化为自我慈悲的任务，却可能让人感到不堪重负或难以接受。来访者和治疗师都没有一套语言，能够解释在来访者心智与身体内部上演的内在挣扎。在一个拒绝承认人格与身份可以碎裂化、分隔化的心理健康世界里，治疗师鲜少受过识别这些分裂的训练，更遑论看见那些目标与本能截然相反的"自我"之间你死我活的控制权争夺。</p>
<p class="indent">My intention in writing this book was to share a way of conceptualizing the most complex and challenging clients who come to us, often carrying &#8220;terminal&#8221; diagnoses, such as personality disorder, bipolar II, even schizophrenia. Over three decades in the trauma treatment field, my compatriots and I have learned about trauma &#8220;the hard way,&#8221; by letting the clients teach us about their inner worlds, their intrusive, overwhelming symptoms, what it is like to live in a body organized to expect annihilation or abandonment. Lacking approaches specifically tailored to the needs of traumatized clients, all of us &#8220;winged it,&#8221; creating new techniques and interventions, seeing what &#8220;worked,&#8221; and retaining what did&#8212;either because the interventions were effective or because the clients liked how they felt.</p>
<p class="indent trans-zh" lang="zh-CN">写作本书的初衷，是分享一种概念化框架，用以理解那些来到我们面前、最为复杂且最具挑战性的来访者——他们往往背负着"终极性"诊断，如人格障碍、双相II型障碍，甚至精神分裂症。在创伤治疗领域浸润三十余年，我与同仁们以最艰难的方式学习创伤——让来访者教导我们他们的内心世界、那些侵入性的、排山倒海的症状，以及活在一个预设着毁灭或遗弃的身体里究竟是怎样一种体验。由于缺乏专门针对创伤来访者需求的方法，我们所有人都只能"摸索前行"，创造新的技术与干预手段，观察什么"有效"，并保留那些有效的——无论是因为干预本身起效，还是因为来访者喜欢它所带来的感受。</p>
<p class="indent">In the 1990s, as an instructor and supervisor at Bessel van der Kolk&#8217;s Trauma Center, I was profoundly influenced by the neuroscience research that began to revolutionize our way of understanding trauma and by Bessel&#8217;s belief that &#8220;the body keeps the score&#8221; (Van der Kolk, 2014). We began then to see trauma-related disorders not as disorders of events but as disorders of the body, brain, and nervous system. The neurobiological lens also resulted in another paradigm shift: if the brain and body are inherently adaptive, then the legacy of trauma responses must also reflect an attempt at adaptation, rather than evidence of pathology.</p>
<p class="indent trans-zh" lang="zh-CN">20世纪90年代，作为Bessel van der Kolk创伤中心的讲师和督导，我深受那场开始颠覆我们创伤理解方式的神经科学研究的影响，也深受Bessel"身体铭记着一切"这一信念的熏陶（Van der Kolk，2014）。我们由此开始将创伤相关障碍视为身体、大脑和神经系统的障碍，而非事件本身的障碍。神经生物学视角也催生了另一次范式转变：如果大脑和身体本质上具有适应性，那么创伤反应的遗留必定也反映着一种适应的尝试，而非病理的证据。</p>
<p class="indent"><span epub:type="pagebreak" id="page_2"/>Through that neurobiological lens, what appears clinically as stuckness and resistance, untreatable diagnoses, or character-disordered behavior simply represent how an individual&#8217;s mind and body adapted to a dangerous world in which the only &#8220;protection&#8221; was the very same caretaker who endangered him or her. Each symptom was an ingenious solution by the body to create some semblance of safety for the developing child or endangered adult. The trauma-related issues with which the client presents for help, I now believe, are in truth a &#8220;red badge of courage&#8221; that tell the story of what happened even more eloquently than the events each individual consciously remembers.</p>
<p class="indent trans-zh" lang="zh-CN">透过神经生物学的视角，那些在临床上表现为停滞和阻抗、难以治疗的诊断或人格障碍行为的现象，不过是个体的心智与身体在一个危险世界中适应的方式——在那个世界里，唯一的"保护"恰恰来自同一个使他或她身陷险境的照料者。每一个症状，都是身体为正在发展中的孩子或身处险境的成人创造某种安全感的精妙解决方案。我现在相信，来访者带来求助的创伤相关问题，实则是一枚"勇敢的红色徽章"，它们讲述所发生之事的方式，比每个人有意识记忆中的事件更加雄辩。</p>
<p class="indent">As I came to be known as an expert in treating trauma, increasing numbers of clients sought me out for consultation, asking, &#8220;Why am I not getting better? My therapist and I have a wonderful relationship, but none of my symptoms are diminishing. Am I doing the wrong kind of therapy? Or is there something wrong with me?&#8221; Time after time, as I heard from clients and therapists what had been tried and failed, I could not find a &#8220;mistake&#8221; or misguided choice of treatment. More often, what could be seen from the consultant&#8217;s perspective was something both therapist and client could not see: the client was fragmented. What it had taken to adapt was a splitting of self and identity sufficiently severe that the individual&#8217;s inner world had become a war zone. What I also noticed was the relief these clients experienced as I educated them about dissociative splitting as a normal adaptation to trauma. First describing to them the theory of Structural Dissociation (Van der Hart, Nijenhuis &amp; Steele, 2006), I would then translate their struggles using the language of parts and the language of animal defense survival responses, the cornerstone of the Structural Dissociation theory. Often, as I spoke, I observed a look of recognition on their faces, as if I were telling them nothing new but simply giving them a language to describe at long last what they already recognized but had no words to explain. Rather than feeling stigmatized or &#8220;crazier,&#8221; the Structural Dissociation model seemed to be reassuring to them. Its central principle, that splitting had simply allowed them to adapt and survive more successfully in an unsafe world, helped even very proud, narcissistic individuals to experience the fragmentation as a validation of their survival, not further proof of their defectiveness.</p>
<p class="indent trans-zh" lang="zh-CN">随着我在创伤治疗领域的专家声誉日渐建立，越来越多的来访者找到我寻求咨询，他们问道："为什么我没有好转？我和治疗师的关系很好，但我的症状没有一点减轻。我是在做错误的治疗吗？还是我本身有什么问题？"一次又一次，当我从来访者和治疗师那里听到已经尝试过但失败了的一切时，我找不到任何"错误"或治疗选择上的失误。更多时候，从咨询师的视角可以看到一些治疗师和来访者都无法看见的东西：来访者是碎裂的。这种适应所需要的，是一种严重到足以让个体内心世界变成战场的自我与身份分裂。我还注意到，当我向这些来访者介绍解离性分裂是对创伤的正常适应时，他们所体验到的释然。首先向他们描述结构性解离理论（Van der Hart, Nijenhuis和Steele，2006），我随后用"部分"的语言和动物防御生存反应的语言——结构性解离理论的基石——来诠释他们的挣扎。往往，在我讲述的过程中，我观察到他们脸上浮现出一种认出的神情，仿佛我所说的并非什么新鲜事，只是给了他们一种语言，终于能够描述他们早已认出却无言以名的东西。结构性解离模型非但没有让他们感到被污名化或"更疯狂"，反而似乎给了他们安慰。其核心原则——分裂只是让他们能够在不安全的世界中更成功地适应和生存——甚至帮助那些非常自尊、自恋的个体，将碎裂化体验为对其生存的认可，而非对其缺陷性的进一步证明。</p>
<p class="indent">As I worked in this way with a range of clients, it became increasingly clear that when they &#8220;adopted&#8221; or came to love their hurt, lost, and lonely parts, something remarkable happened. Their self-disparagement, self-hatred, and disconnection began spontaneously to yield to self-compassion. Whereas the idea of being &#8220;nice,&#8221; &#8220;taking care of&#8221; or being &#8220;compassionate&#8221; to <em>themselves</em> was met with disgust and avoidance, every client could be helped to &#8220;see&#8221; his or her child parts and to extend kindness and care. And as they developed internal attachment relationships to these young selves, I could see them healing.</p>
<p class="indent trans-zh" lang="zh-CN">当我以这种方式与各类来访者工作时，越来越清晰地看到：当他们"收养"或开始爱上自己受伤、迷失和孤独的部分时，某种非凡的事情发生了。他们的自我贬低、自我憎恨和断离感，开始自发地向自我慈悲让步。尽管对<em>自己</em>"好"、"照顾"自己或对自己"充满慈悲"的想法往往引发厌恶和回避，但每一位来访者都能被引导去"看见"自己的儿童部分，并向其延伸善意与关怀。而随着他们与这些年幼的自我发展出内在依恋关系，我能看见他们在愈合。</p>
<p class="indent">What it means to &#8220;heal&#8221; is subjective, of course: for some clients, it implies the ability to function again, to simply reclaim their lives. But, as I observed the clients who began forming loving attachment bonds to their young selves, <span epub:type="pagebreak" id="page_3"/>I could see healing at a much deeper level. Seeing them &#8220;bond&#8221; with the child they had once been and feeling their shame and self-hatred melt away convinced me that the left brain &#8220;adult&#8221; side of each one was capable of relating to the right brain &#8220;child&#8221; side, experiencing him or her as innocent and little, spontaneously evoking warmth and protectiveness. By bonding to the lost children inside, their internal states transformed, creating a warm, loving environment that felt safe at last. Best of all, it was evident that this work was not only transformative but also easy for the clients once they learned the basic skills needed to form internal attachment relationships to their parts.</p>
<p class="indent trans-zh" lang="zh-CN">"愈合"意味着什么，当然是主观的：对某些来访者而言，它意味着重新能够正常运作，简单地夺回自己的生活。但当我观察那些开始与年幼自我建立爱的依恋纽带的来访者时，我看到了更深层次的愈合。看见他们与曾经的那个孩子"联结"，感受到他们的羞耻感和自我憎恨渐渐消融，这让我确信：每个人左脑的"成人"一侧，都有能力与右脑的"儿童"一侧建立关系，将其体验为无辜而幼小，自发地唤起温暖与保护欲。通过与内在那些迷失的孩子建立联结，他们的内在状态发生了转化，创造出一个温暖、充满爱的环境，终于让人感到安全。最重要的是，显而易见的是，一旦来访者学会了与自己的部分建立内在依恋关系所需的基本技能，这项工作不仅具有转化性，而且对他们来说也是轻松可及的。</p>
<p class="indent">The book is intended for use by a wide range of therapists and for an even wider range of clients. In writing it, I hoped particularly to address the challenges faced by chronically traumatized individuals much like those who have sought me out for consultations. These are clients young and old who battle to recover from their legacies of trauma, confused that these have not resolved despite good therapy, effective treatments, supportive relationships, or even rich full lives in the present. I also wanted to describe an effective and respectful way of working with traumatized clients who have lost their hope and ability to function or who depend upon hospitals, families, and loved ones to care for them as they struggle with self-destructive impulses driving suicidal, self-harming, addicted, or eating disordered behavior. Despite decades of research attesting to the relationship between early abuse and a later diagnosis of borderline personality disorder, it is rare for clients with borderline diagnoses to be treated as trauma patients or to be recognized as individuals whose &#8220;borderline&#8221; symptoms stem logically and tragically from the unsafe environments of their early lives. Thanks to enlightened Departments of Mental Health in the states of Massachusetts and Connecticut, I have had the invaluable opportunity to try out the treatment model described in this book with some of their most high-risk patients and to find that, with a treatment model organized around trauma-related splitting and compartmentalization, these patients could begin to stabilize, to live outside of institutional walls, and to understand their attacks on the body as a valiant attempt by one part to gain quick short-term relief from the painful implicit memories of other parts. This book is also meant for traumatized clients who have &#8220;overcome,&#8221; who have prestigious jobs and loving families of choice, whose lives are rich and full, but who still struggle to <em>enjoy</em> the quality of life they have fought to create. And the book is also intended to offer hope to individuals who may be stable but whose internal quality of life is still as dark and painful as the traumatic past despite the safety, support, and meaningful work in their external lives.</p>
<p class="indent trans-zh" lang="zh-CN">本书旨在供各类治疗师及更广泛的来访者群体使用。在撰写过程中，我特别希望回应那些慢性创伤个体所面临的挑战——他们与那些来找我咨询的来访者颇为相似。这些来访者无论老幼，都在艰难挣扎，试图从创伤的遗留中恢复，却困惑于为何即便经历了良好的治疗、有效的疗法、支持性的关系，甚至目前生活富足充实，这些创伤仍未消解。我也想描述一种有效且尊重来访者的工作方式，用于那些已失去希望与功能能力的创伤来访者，或那些在与驱动自杀、自伤、成瘾或进食障碍行为的自毁冲动抗争时，依赖医院、家人和爱人照料的来访者。尽管数十年的研究证实了早期虐待与日后边缘型人格障碍诊断之间的关系，但被诊断为边缘型人格障碍的来访者却鲜少被当作创伤患者对待，也鲜少被视为那些"边缘型"症状在逻辑上、悲剧性地源于其早期不安全环境的个体。感谢马萨诸塞州和康涅狄格州开明的心理健康部门，我获得了宝贵的机会，将本书所描述的治疗模式在一些高风险患者身上加以实践，并发现：以创伤相关分裂和分隔化为核心组织的治疗模式，能够帮助这些患者开始趋于稳定，在机构围墙之外生活，并将对身体的攻击理解为某一部分试图从其他部分痛苦的内隐记忆中获得快速短期解脱的英勇尝试。本书也是为那些已经"克服困难"的创伤来访者而写——他们有着令人瞩目的工作和自己选择的充满爱的家庭，生活丰富而充实，却仍在努力<em>享受</em>他们拼搏所创造的生活品质。本书同样旨在为那些虽然稳定，但其内在生活品质依然与外部生活的安全、支持和有意义的工作相悖、仍像创伤过去一样黑暗痛苦的个体提供希望。</p>
<p class="indent">The treatment paradigm described in this book is not intended for the treatment of any one particular diagnosis. It is meant to be used with and on behalf of all survivors of trauma, whether the client carries a diagnosis of post-traumatic stress disorder (PTSD), has been given a common trauma-related diagnosis such as ADHD, bipolar disorder, borderline personality, or a dissociative disorder, or has never met a mental health professional. If you, the reader, have been failed, attacked, threatened, abandoned, terrorized, or <span epub:type="pagebreak" id="page_4"/>abused by other human beings, and if you still carry with you the emotional and physical legacy of those experiences, or if you work to help those who do, I believe this book will speak to you.</p>
<p class="indent trans-zh" lang="zh-CN">本书所描述的治疗范式，并非针对任何特定诊断的治疗。它旨在被用于所有创伤幸存者及为他们服务——无论来访者是否携带创伤后应激障碍（PTSD）的诊断，是否被给予常见的创伤相关诊断如ADHD、双相障碍、边缘型人格或解离障碍，或者是否从未接触过心理健康专业人员。如果您，读者，曾被他人辜负、攻击、威胁、遗弃、恐吓或虐待，而您仍然带着那些经历的情感与身体遗留，或者您正在帮助那些有此经历的人，我相信这本书会与您产生共鸣。</p>
</div>
''')
out.close()
print("Part A written.")
